package nme;


import openfl.Assets;


class AssetData {
	
	
	public static var library:Map <String, LibraryType>;
	public static var path:Map <String, String>;
	public static var type:Map <String, AssetType>;
	
	private static var initialized:Bool = false;
	
	
	public static function initialize ():Void {
		
		if (!initialized) {
			
			path = new Map<String, String> ();
			type = new Map<String, AssetType> ();
			library = new Map<String, LibraryType> ();
			
			path.set ("Beep", "Beep");
			type.set ("Beep", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/bg_cave.png", "assets_bg_cave_png");
			type.set ("assets/bg_cave.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/bullet.png", "assets_bullet_png");
			type.set ("assets/bullet.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/autotiles.png", "assets_data_autotiles_png");
			type.set ("assets/data/autotiles.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/autotiles_alt.png", "assets_data_autotiles_alt_png");
			type.set ("assets/data/autotiles_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/base.png", "assets_data_base_png");
			type.set ("assets/data/base.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/beep.mp3", "assets/data/beep.mp3");
			type.set ("assets/data/beep.mp3", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/data/beep.wav", "assets/data/beep.wav");
			type.set ("assets/data/beep.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/data/button.png", "assets_data_button_png");
			type.set ("assets/data/button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/button_a.png", "assets_data_button_a_png");
			type.set ("assets/data/button_a.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/button_b.png", "assets_data_button_b_png");
			type.set ("assets/data/button_b.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/button_c.png", "assets_data_button_c_png");
			type.set ("assets/data/button_c.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/button_down.png", "assets_data_button_down_png");
			type.set ("assets/data/button_down.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/button_left.png", "assets_data_button_left_png");
			type.set ("assets/data/button_left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/button_right.png", "assets_data_button_right_png");
			type.set ("assets/data/button_right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/button_up.png", "assets_data_button_up_png");
			type.set ("assets/data/button_up.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/button_x.png", "assets_data_button_x_png");
			type.set ("assets/data/button_x.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/button_y.png", "assets_data_button_y_png");
			type.set ("assets/data/button_y.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/courier.ttf", "assets_data_courier_ttf");
			type.set ("assets/data/courier.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/data/cursor.png", "assets_data_cursor_png");
			type.set ("assets/data/cursor.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/default.png", "assets_data_default_png");
			type.set ("assets/data/default.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/fontData10pt.png", "assets_data_fontdata10pt_png");
			type.set ("assets/data/fontData10pt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/fontData11pt.png", "assets_data_fontdata11pt_png");
			type.set ("assets/data/fontData11pt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/handle.png", "assets_data_handle_png");
			type.set ("assets/data/handle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/logo.png", "assets_data_logo_png");
			type.set ("assets/data/logo.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/logo_corners.png", "assets_data_logo_corners_png");
			type.set ("assets/data/logo_corners.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/logo_light.png", "assets_data_logo_light_png");
			type.set ("assets/data/logo_light.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/nokiafc22.ttf", "assets_data_nokiafc22_ttf");
			type.set ("assets/data/nokiafc22.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/data/stick.png", "assets_data_stick_png");
			type.set ("assets/data/stick.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/vcr/flixel.png", "assets_data_vcr_flixel_png");
			type.set ("assets/data/vcr/flixel.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/vcr/open.png", "assets_data_vcr_open_png");
			type.set ("assets/data/vcr/open.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/vcr/pause.png", "assets_data_vcr_pause_png");
			type.set ("assets/data/vcr/pause.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/vcr/play.png", "assets_data_vcr_play_png");
			type.set ("assets/data/vcr/play.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/vcr/record_off.png", "assets_data_vcr_record_off_png");
			type.set ("assets/data/vcr/record_off.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/vcr/record_on.png", "assets_data_vcr_record_on_png");
			type.set ("assets/data/vcr/record_on.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/vcr/restart.png", "assets_data_vcr_restart_png");
			type.set ("assets/data/vcr/restart.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/vcr/step.png", "assets_data_vcr_step_png");
			type.set ("assets/data/vcr/step.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/vcr/stop.png", "assets_data_vcr_stop_png");
			type.set ("assets/data/vcr/stop.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/data/vis/bounds.png", "assets_data_vis_bounds_png");
			type.set ("assets/data/vis/bounds.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Fonts/kenpixel.ttf", "assets_fonts_kenpixel_ttf");
			type.set ("assets/Fonts/kenpixel.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/Fonts/kenpixel_blocks.ttf", "assets_fonts_kenpixel_blocks_ttf");
			type.set ("assets/Fonts/kenpixel_blocks.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/Fonts/kenpixel_future.ttf", "assets_fonts_kenpixel_future_ttf");
			type.set ("assets/Fonts/kenpixel_future.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/Fonts/kenpixel_future_square.ttf", "assets_fonts_kenpixel_future_square_ttf");
			type.set ("assets/Fonts/kenpixel_future_square.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/Fonts/kenpixel_high.ttf", "assets_fonts_kenpixel_high_ttf");
			type.set ("assets/Fonts/kenpixel_high.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/Fonts/kenpixel_high_square.ttf", "assets_fonts_kenpixel_high_square_ttf");
			type.set ("assets/Fonts/kenpixel_high_square.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/Fonts/kenpixel_mini.ttf", "assets_fonts_kenpixel_mini_ttf");
			type.set ("assets/Fonts/kenpixel_mini.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/Fonts/kenpixel_mini_square.ttf", "assets_fonts_kenpixel_mini_square_ttf");
			type.set ("assets/Fonts/kenpixel_mini_square.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/Fonts/kenpixel_square.ttf", "assets_fonts_kenpixel_square_ttf");
			type.set ("assets/Fonts/kenpixel_square.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/Fonts/license.txt", "assets_fonts_license_txt");
			type.set ("assets/Fonts/license.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/gfx/caveWallTiles.png", "assets_gfx_cavewalltiles_png");
			type.set ("assets/gfx/caveWallTiles.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/citizen.png", "assets_gfx_citizen_png");
			type.set ("assets/gfx/citizen.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/mountain.png", "assets_gfx_mountain_png");
			type.set ("assets/gfx/mountain.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/snow.png", "assets_gfx_snow_png");
			type.set ("assets/gfx/snow.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/spaceman.png", "assets_gfx_spaceman_png");
			type.set ("assets/gfx/spaceman.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/gfx/wood.png", "assets_gfx_wood_png");
			type.set ("assets/gfx/wood.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/HaxeFlixel.svg", "assets_haxeflixel_svg");
			type.set ("assets/HaxeFlixel.svg", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/map.txt", "assets_map_txt");
			type.set ("assets/map.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/player.png", "assets_player_png");
			type.set ("assets/player.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/player_gibs.png", "assets_player_gibs_png");
			type.set ("assets/player_gibs.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/tiles.png", "assets_tiles_png");
			type.set ("assets/tiles.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/tileset.png", "assets_tileset_png");
			type.set ("assets/tileset.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/debugger/buttons/console.png", "flixel_img_debugger_buttons_console_png");
			type.set ("flixel/img/debugger/buttons/console.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/debugger/buttons/logDebug.png", "flixel_img_debugger_buttons_logdebug_png");
			type.set ("flixel/img/debugger/buttons/logDebug.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/debugger/buttons/open.png", "flixel_img_debugger_buttons_open_png");
			type.set ("flixel/img/debugger/buttons/open.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/debugger/buttons/pause.png", "flixel_img_debugger_buttons_pause_png");
			type.set ("flixel/img/debugger/buttons/pause.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/debugger/buttons/play.png", "flixel_img_debugger_buttons_play_png");
			type.set ("flixel/img/debugger/buttons/play.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/debugger/buttons/record_off.png", "flixel_img_debugger_buttons_record_off_png");
			type.set ("flixel/img/debugger/buttons/record_off.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/debugger/buttons/record_on.png", "flixel_img_debugger_buttons_record_on_png");
			type.set ("flixel/img/debugger/buttons/record_on.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/debugger/buttons/restart.png", "flixel_img_debugger_buttons_restart_png");
			type.set ("flixel/img/debugger/buttons/restart.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/debugger/buttons/statsDebug.png", "flixel_img_debugger_buttons_statsdebug_png");
			type.set ("flixel/img/debugger/buttons/statsDebug.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/debugger/buttons/step.png", "flixel_img_debugger_buttons_step_png");
			type.set ("flixel/img/debugger/buttons/step.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/debugger/buttons/stop.png", "flixel_img_debugger_buttons_stop_png");
			type.set ("flixel/img/debugger/buttons/stop.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/debugger/buttons/visualDebug.png", "flixel_img_debugger_buttons_visualdebug_png");
			type.set ("flixel/img/debugger/buttons/visualDebug.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/debugger/buttons/watchDebug.png", "flixel_img_debugger_buttons_watchdebug_png");
			type.set ("flixel/img/debugger/buttons/watchDebug.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/debugger/flixel.png", "flixel_img_debugger_flixel_png");
			type.set ("flixel/img/debugger/flixel.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/debugger/windowHandle.png", "flixel_img_debugger_windowhandle_png");
			type.set ("flixel/img/debugger/windowHandle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/logo/default.png", "flixel_img_logo_default_png");
			type.set ("flixel/img/logo/default.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/logo/HaxeFlixel.svg", "flixel_img_logo_haxeflixel_svg");
			type.set ("flixel/img/logo/HaxeFlixel.svg", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("flixel/img/logo/logo.png", "flixel_img_logo_logo_png");
			type.set ("flixel/img/logo/logo.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/preloader/corners.png", "flixel_img_preloader_corners_png");
			type.set ("flixel/img/preloader/corners.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/preloader/light.png", "flixel_img_preloader_light_png");
			type.set ("flixel/img/preloader/light.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/tile/autotiles.png", "flixel_img_tile_autotiles_png");
			type.set ("flixel/img/tile/autotiles.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/tile/autotiles_alt.png", "flixel_img_tile_autotiles_alt_png");
			type.set ("flixel/img/tile/autotiles_alt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/ui/analog/base.png", "flixel_img_ui_analog_base_png");
			type.set ("flixel/img/ui/analog/base.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/ui/analog/thumb.png", "flixel_img_ui_analog_thumb_png");
			type.set ("flixel/img/ui/analog/thumb.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/ui/button.png", "flixel_img_ui_button_png");
			type.set ("flixel/img/ui/button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/ui/cursor.png", "flixel_img_ui_cursor_png");
			type.set ("flixel/img/ui/cursor.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/ui/fontData11pt.png", "flixel_img_ui_fontdata11pt_png");
			type.set ("flixel/img/ui/fontData11pt.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/ui/virtualpad/a.png", "flixel_img_ui_virtualpad_a_png");
			type.set ("flixel/img/ui/virtualpad/a.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/ui/virtualpad/b.png", "flixel_img_ui_virtualpad_b_png");
			type.set ("flixel/img/ui/virtualpad/b.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/ui/virtualpad/c.png", "flixel_img_ui_virtualpad_c_png");
			type.set ("flixel/img/ui/virtualpad/c.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/ui/virtualpad/down.png", "flixel_img_ui_virtualpad_down_png");
			type.set ("flixel/img/ui/virtualpad/down.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/ui/virtualpad/left.png", "flixel_img_ui_virtualpad_left_png");
			type.set ("flixel/img/ui/virtualpad/left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/ui/virtualpad/right.png", "flixel_img_ui_virtualpad_right_png");
			type.set ("flixel/img/ui/virtualpad/right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/ui/virtualpad/up.png", "flixel_img_ui_virtualpad_up_png");
			type.set ("flixel/img/ui/virtualpad/up.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/ui/virtualpad/x.png", "flixel_img_ui_virtualpad_x_png");
			type.set ("flixel/img/ui/virtualpad/x.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/img/ui/virtualpad/y.png", "flixel_img_ui_virtualpad_y_png");
			type.set ("flixel/img/ui/virtualpad/y.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/snd/beep.wav", "flixel/snd/beep.wav");
			type.set ("flixel/snd/beep.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("flixel/snd/flixel.wav", "flixel/snd/flixel.wav");
			type.set ("flixel/snd/flixel.wav", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/box.png", "flixel_flixel_ui_img_box_png");
			type.set ("flixel/flixel-ui/img/box.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button.png", "flixel_flixel_ui_img_button_png");
			type.set ("flixel/flixel-ui/img/button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button_thin.png", "flixel_flixel_ui_img_button_thin_png");
			type.set ("flixel/flixel-ui/img/button_thin.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/button_toggle.png", "flixel_flixel_ui_img_button_toggle_png");
			type.set ("flixel/flixel-ui/img/button_toggle.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/check_box.png", "flixel_flixel_ui_img_check_box_png");
			type.set ("flixel/flixel-ui/img/check_box.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/check_mark.png", "flixel_flixel_ui_img_check_mark_png");
			type.set ("flixel/flixel-ui/img/check_mark.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/chrome.png", "flixel_flixel_ui_img_chrome_png");
			type.set ("flixel/flixel-ui/img/chrome.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/chrome_flat.png", "flixel_flixel_ui_img_chrome_flat_png");
			type.set ("flixel/flixel-ui/img/chrome_flat.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/chrome_inset.png", "flixel_flixel_ui_img_chrome_inset_png");
			type.set ("flixel/flixel-ui/img/chrome_inset.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/dropdown_mark.png", "flixel_flixel_ui_img_dropdown_mark_png");
			type.set ("flixel/flixel-ui/img/dropdown_mark.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/hilight.png", "flixel_flixel_ui_img_hilight_png");
			type.set ("flixel/flixel-ui/img/hilight.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/invis.png", "flixel_flixel_ui_img_invis_png");
			type.set ("flixel/flixel-ui/img/invis.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/radio.png", "flixel_flixel_ui_img_radio_png");
			type.set ("flixel/flixel-ui/img/radio.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/radio_dot.png", "flixel_flixel_ui_img_radio_dot_png");
			type.set ("flixel/flixel-ui/img/radio_dot.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/tab.png", "flixel_flixel_ui_img_tab_png");
			type.set ("flixel/flixel-ui/img/tab.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/img/tab_back.png", "flixel_flixel_ui_img_tab_back_png");
			type.set ("flixel/flixel-ui/img/tab_back.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("flixel/flixel-ui/xml/defaults.xml", "flixel_flixel_ui_xml_defaults_xml");
			type.set ("flixel/flixel-ui/xml/defaults.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("flixel/flixel-ui/xml/default_popup.xml", "flixel_flixel_ui_xml_default_popup_xml");
			type.set ("flixel/flixel-ui/xml/default_popup.xml", Reflect.field (AssetType, "text".toUpperCase ()));
			
			
			initialized = true;
			
		}
		
	}
	
	
}